### ISSUE TITLE
Add support for alternative ID port and maskinporten environments

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#170] opened 2023-01-12 06:32 UTC
### Description

When ID-porten changes infrastructure there will be a new maskinporten and  ID-porten endpoints where tokens will be generated from. 

Both new and old environments will be used at the same time. Altinn Authentication needs to be updated to support this.

### Acceptance Criterias

- [ ] Authentication needs to support multiple ID-porten environments
- [ ] Authentication needs to support multiple maskinporten environments

**Comment by jonkjetiloye** [comment] 2023-02-09 12:43
@Sondre-B Isn't this merged and can be moved to test?

**Comment by Sondre-B** [comment] 2023-02-09 12:46
@jonkjetiloye No this is still waiting for review. https://github.com/Altinn/altinn-authentication/pull/189

**Comment by jonkjetiloye** [comment] 2023-06-01 07:37
@TheTechArch @Sondre-B 
Marked as Done in [Team Tilgangsinfo](https://github.com/orgs/Altinn/projects/75) but left in Test for [Team Tilgangsstyring & Kontroll](https://github.com/orgs/Altinn/projects/50) and the issue is still open.

I'll leave it up to you guys to evaluate whether it's been tested and close the issue

**Closed** 2024-10-25 10:43 UTC
Labels: kind/user-story
